-- =============================================
-- Script SQL pour insérer tous les pays du monde
-- Table: public.countries
-- =============================================

-- Vider la table existante (optionnel - décommentez si nécessaire)
-- TRUNCATE TABLE public.countries CASCADE;

-- Insertion des pays
INSERT INTO public.countries (code, name_fr, name_en, continent, is_francophone) VALUES
-- AFRIQUE
('DZ', 'Algérie', 'Algeria', 'Africa', true),
('AO', 'Angola', 'Angola', 'Africa', false),
('BJ', 'Bénin', 'Benin', 'Africa', true),
('BW', 'Botswana', 'Botswana', 'Africa', false),
('BF', 'Burkina Faso', 'Burkina Faso', 'Africa', true),
('BI', 'Burundi', 'Burundi', 'Africa', true),
('CM', 'Cameroun', 'Cameroon', 'Africa', true),
('CV', 'Cap-Vert', 'Cape Verde', 'Africa', false),
('CF', 'République centrafricaine', 'Central African Republic', 'Africa', true),
('TD', 'Tchad', 'Chad', 'Africa', true),
('KM', 'Comores', 'Comoros', 'Africa', true),
('CG', 'Congo', 'Congo', 'Africa', true),
('CD', 'République démocratique du Congo', 'Democratic Republic of the Congo', 'Africa', true),
('DJ', 'Djibouti', 'Djibouti', 'Africa', true),
('EG', 'Égypte', 'Egypt', 'Africa', false),
('GQ', 'Guinée équatoriale', 'Equatorial Guinea', 'Africa', true),
('ER', 'Érythrée', 'Eritrea', 'Africa', false),
('SZ', 'Eswatini', 'Eswatini', 'Africa', false),
('ET', 'Éthiopie', 'Ethiopia', 'Africa', false),
('GA', 'Gabon', 'Gabon', 'Africa', true),
('GM', 'Gambie', 'Gambia', 'Africa', false),
('GH', 'Ghana', 'Ghana', 'Africa', false),
('GN', 'Guinée', 'Guinea', 'Africa', true),
('GW', 'Guinée-Bissau', 'Guinea-Bissau', 'Africa', false),
('CI', 'Côte d''Ivoire', 'Ivory Coast', 'Africa', true),
('KE', 'Kenya', 'Kenya', 'Africa', false),
('LS', 'Lesotho', 'Lesotho', 'Africa', false),
('LR', 'Liberia', 'Liberia', 'Africa', false),
('LY', 'Libye', 'Libya', 'Africa', false),
('MG', 'Madagascar', 'Madagascar', 'Africa', true),
('MW', 'Malawi', 'Malawi', 'Africa', false),
('ML', 'Mali', 'Mali', 'Africa', true),
('MR', 'Mauritanie', 'Mauritania', 'Africa', true),
('MU', 'Maurice', 'Mauritius', 'Africa', true),
('MA', 'Maroc', 'Morocco', 'Africa', true),
('MZ', 'Mozambique', 'Mozambique', 'Africa', false),
('NA', 'Namibie', 'Namibia', 'Africa', false),
('NE', 'Niger', 'Niger', 'Africa', true),
('NG', 'Nigeria', 'Nigeria', 'Africa', false),
('RW', 'Rwanda', 'Rwanda', 'Africa', true),
('ST', 'Sao Tomé-et-Principe', 'Sao Tome and Principe', 'Africa', false),
('SN', 'Sénégal', 'Senegal', 'Africa', true),
('SC', 'Seychelles', 'Seychelles', 'Africa', true),
('SL', 'Sierra Leone', 'Sierra Leone', 'Africa', false),
('SO', 'Somalie', 'Somalia', 'Africa', false),
('ZA', 'Afrique du Sud', 'South Africa', 'Africa', false),
('SS', 'Soudan du Sud', 'South Sudan', 'Africa', false),
('SD', 'Soudan', 'Sudan', 'Africa', false),
('TZ', 'Tanzanie', 'Tanzania', 'Africa', false),
('TG', 'Togo', 'Togo', 'Africa', true),
('TN', 'Tunisie', 'Tunisia', 'Africa', true),
('UG', 'Ouganda', 'Uganda', 'Africa', false),
('ZM', 'Zambie', 'Zambia', 'Africa', false),
('ZW', 'Zimbabwe', 'Zimbabwe', 'Africa', false),

-- AMÉRIQUE DU NORD
('AG', 'Antigua-et-Barbuda', 'Antigua and Barbuda', 'North America', false),
('BS', 'Bahamas', 'Bahamas', 'North America', false),
('BB', 'Barbade', 'Barbados', 'North America', false),
('BZ', 'Belize', 'Belize', 'North America', false),
('CA', 'Canada', 'Canada', 'North America', true),
('CR', 'Costa Rica', 'Costa Rica', 'North America', false),
('CU', 'Cuba', 'Cuba', 'North America', false),
('DM', 'Dominique', 'Dominica', 'North America', false),
('DO', 'République dominicaine', 'Dominican Republic', 'North America', false),
('SV', 'El Salvador', 'El Salvador', 'North America', false),
('GD', 'Grenade', 'Grenada', 'North America', false),
('GT', 'Guatemala', 'Guatemala', 'North America', false),
('HT', 'Haïti', 'Haiti', 'North America', true),
('HN', 'Honduras', 'Honduras', 'North America', false),
('JM', 'Jamaïque', 'Jamaica', 'North America', false),
('MX', 'Mexique', 'Mexico', 'North America', false),
('NI', 'Nicaragua', 'Nicaragua', 'North America', false),
('PA', 'Panama', 'Panama', 'North America', false),
('KN', 'Saint-Christophe-et-Niévès', 'Saint Kitts and Nevis', 'North America', false),
('LC', 'Sainte-Lucie', 'Saint Lucia', 'North America', false),
('VC', 'Saint-Vincent-et-les-Grenadines', 'Saint Vincent and the Grenadines', 'North America', false),
('TT', 'Trinité-et-Tobago', 'Trinidad and Tobago', 'North America', false),
('US', 'États-Unis', 'United States', 'North America', false),

-- AMÉRIQUE DU SUD
('AR', 'Argentine', 'Argentina', 'South America', false),
('BO', 'Bolivie', 'Bolivia', 'South America', false),
('BR', 'Brésil', 'Brazil', 'South America', false),
('CL', 'Chili', 'Chile', 'South America', false),
('CO', 'Colombie', 'Colombia', 'South America', false),
('EC', 'Équateur', 'Ecuador', 'South America', false),
('GF', 'Guyane française', 'French Guiana', 'South America', true),
('GY', 'Guyana', 'Guyana', 'South America', false),
('PY', 'Paraguay', 'Paraguay', 'South America', false),
('PE', 'Pérou', 'Peru', 'South America', false),
('SR', 'Suriname', 'Suriname', 'South America', false),
('UY', 'Uruguay', 'Uruguay', 'South America', false),
('VE', 'Venezuela', 'Venezuela', 'South America', false),

-- ASIE
('AF', 'Afghanistan', 'Afghanistan', 'Asia', false),
('AM', 'Arménie', 'Armenia', 'Asia', false),
('AZ', 'Azerbaïdjan', 'Azerbaijan', 'Asia', false),
('BH', 'Bahreïn', 'Bahrain', 'Asia', false),
('BD', 'Bangladesh', 'Bangladesh', 'Asia', false),
('BT', 'Bhoutan', 'Bhutan', 'Asia', false),
('BN', 'Brunei', 'Brunei', 'Asia', false),
('KH', 'Cambodge', 'Cambodia', 'Asia', true),
('CN', 'Chine', 'China', 'Asia', false),
('CY', 'Chypre', 'Cyprus', 'Asia', false),
('GE', 'Géorgie', 'Georgia', 'Asia', false),
('IN', 'Inde', 'India', 'Asia', false),
('ID', 'Indonésie', 'Indonesia', 'Asia', false),
('IR', 'Iran', 'Iran', 'Asia', false),
('IQ', 'Irak', 'Iraq', 'Asia', false),
('IL', 'Israël', 'Israel', 'Asia', false),
('JP', 'Japon', 'Japan', 'Asia', false),
('JO', 'Jordanie', 'Jordan', 'Asia', false),
('KZ', 'Kazakhstan', 'Kazakhstan', 'Asia', false),
('KW', 'Koweït', 'Kuwait', 'Asia', false),
('KG', 'Kirghizistan', 'Kyrgyzstan', 'Asia', false),
('LA', 'Laos', 'Laos', 'Asia', true),
('LB', 'Liban', 'Lebanon', 'Asia', true),
('MY', 'Malaisie', 'Malaysia', 'Asia', false),
('MV', 'Maldives', 'Maldives', 'Asia', false),
('MN', 'Mongolie', 'Mongolia', 'Asia', false),
('MM', 'Myanmar', 'Myanmar', 'Asia', false),
('NP', 'Népal', 'Nepal', 'Asia', false),
('KP', 'Corée du Nord', 'North Korea', 'Asia', false),
('OM', 'Oman', 'Oman', 'Asia', false),
('PK', 'Pakistan', 'Pakistan', 'Asia', false),
('PS', 'Palestine', 'Palestine', 'Asia', false),
('PH', 'Philippines', 'Philippines', 'Asia', false),
('QA', 'Qatar', 'Qatar', 'Asia', false),
('SA', 'Arabie saoudite', 'Saudi Arabia', 'Asia', false),
('SG', 'Singapour', 'Singapore', 'Asia', false),
('KR', 'Corée du Sud', 'South Korea', 'Asia', false),
('LK', 'Sri Lanka', 'Sri Lanka', 'Asia', false),
('SY', 'Syrie', 'Syria', 'Asia', false),
('TW', 'Taïwan', 'Taiwan', 'Asia', false),
('TJ', 'Tadjikistan', 'Tajikistan', 'Asia', false),
('TH', 'Thaïlande', 'Thailand', 'Asia', false),
('TL', 'Timor oriental', 'Timor-Leste', 'Asia', false),
('TR', 'Turquie', 'Turkey', 'Asia', false),
('TM', 'Turkménistan', 'Turkmenistan', 'Asia', false),
('AE', 'Émirats arabes unis', 'United Arab Emirates', 'Asia', false),
('UZ', 'Ouzbékistan', 'Uzbekistan', 'Asia', false),
('VN', 'Vietnam', 'Vietnam', 'Asia', true),
('YE', 'Yémen', 'Yemen', 'Asia', false),

-- EUROPE
('AL', 'Albanie', 'Albania', 'Europe', false),
('AD', 'Andorre', 'Andorra', 'Europe', false),
('AT', 'Autriche', 'Austria', 'Europe', false),
('BY', 'Biélorussie', 'Belarus', 'Europe', false),
('BE', 'Belgique', 'Belgium', 'Europe', true),
('BA', 'Bosnie-Herzégovine', 'Bosnia and Herzegovina', 'Europe', false),
('BG', 'Bulgarie', 'Bulgaria', 'Europe', false),
('HR', 'Croatie', 'Croatia', 'Europe', false),
('CZ', 'République tchèque', 'Czech Republic', 'Europe', false),
('DK', 'Danemark', 'Denmark', 'Europe', false),
('EE', 'Estonie', 'Estonia', 'Europe', false),
('FI', 'Finlande', 'Finland', 'Europe', false),
('FR', 'France', 'France', 'Europe', true),
('DE', 'Allemagne', 'Germany', 'Europe', false),
('GR', 'Grèce', 'Greece', 'Europe', false),
('HU', 'Hongrie', 'Hungary', 'Europe', false),
('IS', 'Islande', 'Iceland', 'Europe', false),
('IE', 'Irlande', 'Ireland', 'Europe', false),
('IT', 'Italie', 'Italy', 'Europe', false),
('XK', 'Kosovo', 'Kosovo', 'Europe', false),
('LV', 'Lettonie', 'Latvia', 'Europe', false),
('LI', 'Liechtenstein', 'Liechtenstein', 'Europe', false),
('LT', 'Lituanie', 'Lithuania', 'Europe', false),
('LU', 'Luxembourg', 'Luxembourg', 'Europe', true),
('MT', 'Malte', 'Malta', 'Europe', false),
('MD', 'Moldavie', 'Moldova', 'Europe', false),
('MC', 'Monaco', 'Monaco', 'Europe', true),
('ME', 'Monténégro', 'Montenegro', 'Europe', false),
('NL', 'Pays-Bas', 'Netherlands', 'Europe', false),
('MK', 'Macédoine du Nord', 'North Macedonia', 'Europe', false),
('NO', 'Norvège', 'Norway', 'Europe', false),
('PL', 'Pologne', 'Poland', 'Europe', false),
('PT', 'Portugal', 'Portugal', 'Europe', false),
('RO', 'Roumanie', 'Romania', 'Europe', false),
('RU', 'Russie', 'Russia', 'Europe', false),
('SM', 'Saint-Marin', 'San Marino', 'Europe', false),
('RS', 'Serbie', 'Serbia', 'Europe', false),
('SK', 'Slovaquie', 'Slovakia', 'Europe', false),
('SI', 'Slovénie', 'Slovenia', 'Europe', false),
('ES', 'Espagne', 'Spain', 'Europe', false),
('SE', 'Suède', 'Sweden', 'Europe', false),
('CH', 'Suisse', 'Switzerland', 'Europe', true),
('UA', 'Ukraine', 'Ukraine', 'Europe', false),
('GB', 'Royaume-Uni', 'United Kingdom', 'Europe', false),
('VA', 'Vatican', 'Vatican City', 'Europe', false),

-- OCÉANIE
('AU', 'Australie', 'Australia', 'Oceania', false),
('FJ', 'Fidji', 'Fiji', 'Oceania', false),
('KI', 'Kiribati', 'Kiribati', 'Oceania', false),
('MH', 'Îles Marshall', 'Marshall Islands', 'Oceania', false),
('FM', 'Micronésie', 'Micronesia', 'Oceania', false),
('NR', 'Nauru', 'Nauru', 'Oceania', false),
('NZ', 'Nouvelle-Zélande', 'New Zealand', 'Oceania', false),
('PW', 'Palaos', 'Palau', 'Oceania', false),
('PG', 'Papouasie-Nouvelle-Guinée', 'Papua New Guinea', 'Oceania', false),
('WS', 'Samoa', 'Samoa', 'Oceania', false),
('SB', 'Îles Salomon', 'Solomon Islands', 'Oceania', false),
('TO', 'Tonga', 'Tonga', 'Oceania', false),
('TV', 'Tuvalu', 'Tuvalu', 'Oceania', false),
('VU', 'Vanuatu', 'Vanuatu', 'Oceania', true)
ON CONFLICT (code) DO UPDATE SET
  name_fr = EXCLUDED.name_fr,
  name_en = EXCLUDED.name_en,
  continent = EXCLUDED.continent,
  is_francophone = EXCLUDED.is_francophone;

-- Ajouter quelques territoires et régions spéciales
INSERT INTO public.countries (code, name_fr, name_en, continent, is_francophone) VALUES
('HK', 'Hong Kong', 'Hong Kong', 'Asia', false),
('MO', 'Macao', 'Macau', 'Asia', false),
('PR', 'Porto Rico', 'Puerto Rico', 'North America', false),
('RE', 'La Réunion', 'Réunion', 'Africa', true),
('GP', 'Guadeloupe', 'Guadeloupe', 'North America', true),
('MQ', 'Martinique', 'Martinique', 'North America', true),
('YT', 'Mayotte', 'Mayotte', 'Africa', true),
('NC', 'Nouvelle-Calédonie', 'New Caledonia', 'Oceania', true),
('PF', 'Polynésie française', 'French Polynesia', 'Oceania', true),
('PM', 'Saint-Pierre-et-Miquelon', 'Saint Pierre and Miquelon', 'North America', true),
('WF', 'Wallis-et-Futuna', 'Wallis and Futuna', 'Oceania', true)
ON CONFLICT (code) DO UPDATE SET
  name_fr = EXCLUDED.name_fr,
  name_en = EXCLUDED.name_en,
  continent = EXCLUDED.continent,
  is_francophone = EXCLUDED.is_francophone;

-- Message de confirmation
DO $$
DECLARE
  country_count INTEGER;
  francophone_count INTEGER;
BEGIN
  SELECT COUNT(*) INTO country_count FROM public.countries;
  SELECT COUNT(*) INTO francophone_count FROM public.countries WHERE is_francophone = true;
  
  RAISE NOTICE 'Insertion terminée: % pays au total, dont % pays francophones', country_count, francophone_count;
END $$;